import { markRaw, type Component } from 'vue'
import {
  Home,
  Search,
  Settings,
  User,
  Users,
  Menu,
  Globe,
  Mail,
  MessageSquare,
  Bell,
  Calendar,
  Clock,
  Star,
  Heart,
  Bookmark,
  Folder,
  File,
  Image,
  Camera,
  Map,
  MapPin,
  ShoppingCart,
  CreditCard,
  Phone,
  Share2,
  Download,
  Upload,
  Trash2,
  Edit3,
  Plus,
  Minus,
  Check,
  X,
  PlusCircle,
  MinusCircle,
  CheckCircle,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Shield,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  Link,
  ExternalLink,
  LogIn,
  LogOut,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  Layout,
  Sidebar,
  Maximize2,
  Minimize2,
  Sun,
  Moon,
  Cloud,
  Github,
  Send,
  Inbox,
  Compass,
  Target,
  Flag,
  Award,
  Crown,
  Gem,
  BarChart3,
  PieChart,
  Activity,
  RefreshCw,
  Filter,
  Sliders,
  Eye,
  EyeOff,
  BookOpen,
  Copy,
  Clipboard,
  Toolbox,
  Wrench,
  Package,
  Layers,
  Code,
  Terminal,
  Server,
  Database,
  AtSign,
  Volume2,
  Zap,
  Coffee,
  Gift,
  Tag,
  DollarSign,
  Percent,
  TrendingUp,
  TrendingDown,
  Play,
  Pause,
  Film,
  Headphones,
  Save,
  Undo2,
  Redo2,
  Fingerprint,
  ScrollText,
  Printer,
  Wifi,
  Globe2,
  Navigation,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Expand,
  // Collapse removed in lucide 1.0
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  RotateCw,
  RotateCcw,
  Command,
  GitBranch,
  GitPullRequest,
  GitCommit,
  HardDrive,
  CalendarDays,
  Timer,
  CloudSun,
  CloudMoon,
} from 'lucide-vue-next'

const registry: Record<string, Component> = {
  Home: markRaw(Home),
  Search: markRaw(Search),
  Settings: markRaw(Settings),
  User: markRaw(User),
  Users: markRaw(Users),
  Menu: markRaw(Menu),
  Globe: markRaw(Globe),
  Mail: markRaw(Mail),
  MessageSquare: markRaw(MessageSquare),
  Bell: markRaw(Bell),
  Calendar: markRaw(Calendar),
  Clock: markRaw(Clock),
  Star: markRaw(Star),
  Heart: markRaw(Heart),
  Bookmark: markRaw(Bookmark),
  Folder: markRaw(Folder),
  File: markRaw(File),
  Image: markRaw(Image),
  Camera: markRaw(Camera),
  Map: markRaw(Map),
  MapPin: markRaw(MapPin),
  ShoppingCart: markRaw(ShoppingCart),
  CreditCard: markRaw(CreditCard),
  Phone: markRaw(Phone),
  Share2: markRaw(Share2),
  Download: markRaw(Download),
  Upload: markRaw(Upload),
  Trash2: markRaw(Trash2),
  Edit3: markRaw(Edit3),
  Plus: markRaw(Plus),
  Minus: markRaw(Minus),
  Check: markRaw(Check),
  X: markRaw(X),
  PlusCircle: markRaw(PlusCircle),
  MinusCircle: markRaw(MinusCircle),
  CheckCircle: markRaw(CheckCircle),
  XCircle: markRaw(XCircle),
  AlertCircle: markRaw(AlertCircle),
  AlertTriangle: markRaw(AlertTriangle),
  Info: markRaw(Info),
  HelpCircle: markRaw(HelpCircle),
  Shield: markRaw(Shield),
  ShieldCheck: markRaw(ShieldCheck),
  Lock: markRaw(Lock),
  Unlock: markRaw(Unlock),
  Key: markRaw(Key),
  Link: markRaw(Link),
  ExternalLink: markRaw(ExternalLink),
  LogIn: markRaw(LogIn),
  LogOut: markRaw(LogOut),
  ChevronDown: markRaw(ChevronDown),
  ChevronUp: markRaw(ChevronUp),
  ChevronLeft: markRaw(ChevronLeft),
  ChevronRight: markRaw(ChevronRight),
  ArrowDown: markRaw(ArrowDown),
  ArrowUp: markRaw(ArrowUp),
  ArrowLeft: markRaw(ArrowLeft),
  ArrowRight: markRaw(ArrowRight),
  MoreHorizontal: markRaw(MoreHorizontal),
  MoreVertical: markRaw(MoreVertical),
  Grid: markRaw(Grid),
  List: markRaw(List),
  Layout: markRaw(Layout),
  Sidebar: markRaw(Sidebar),
  Maximize2: markRaw(Maximize2),
  Minimize2: markRaw(Minimize2),
  Sun: markRaw(Sun),
  Moon: markRaw(Moon),
  Cloud: markRaw(Cloud),
  Github: markRaw(Github),
  Send: markRaw(Send),
  Inbox: markRaw(Inbox),
  Compass: markRaw(Compass),
  Target: markRaw(Target),
  Flag: markRaw(Flag),
  Award: markRaw(Award),
  Crown: markRaw(Crown),
  Gem: markRaw(Gem),
  BarChart3: markRaw(BarChart3),
  PieChart: markRaw(PieChart),
  Activity: markRaw(Activity),
  RefreshCw: markRaw(RefreshCw),
  Filter: markRaw(Filter),
  Sliders: markRaw(Sliders),
  Eye: markRaw(Eye),
  EyeOff: markRaw(EyeOff),
  BookOpen: markRaw(BookOpen),
  Copy: markRaw(Copy),
  Clipboard: markRaw(Clipboard),
  Toolbox: markRaw(Toolbox),
  Wrench: markRaw(Wrench),
  Package: markRaw(Package),
  Layers: markRaw(Layers),
  Code: markRaw(Code),
  Terminal: markRaw(Terminal),
  Server: markRaw(Server),
  Database: markRaw(Database),
  AtSign: markRaw(AtSign),
  Volume2: markRaw(Volume2),
  Zap: markRaw(Zap),
  Coffee: markRaw(Coffee),
  Gift: markRaw(Gift),
  Tag: markRaw(Tag),
  DollarSign: markRaw(DollarSign),
  Percent: markRaw(Percent),
  TrendingUp: markRaw(TrendingUp),
  TrendingDown: markRaw(TrendingDown),
  Play: markRaw(Play),
  Pause: markRaw(Pause),
  Film: markRaw(Film),
  Headphones: markRaw(Headphones),
  Save: markRaw(Save),
  Undo2: markRaw(Undo2),
  Redo2: markRaw(Redo2),
  Fingerprint: markRaw(Fingerprint),
  ScrollText: markRaw(ScrollText),
  Printer: markRaw(Printer),
  Wifi: markRaw(Wifi),
  Globe2: markRaw(Globe2),
  Navigation: markRaw(Navigation),
  PanelLeft: markRaw(PanelLeft),
  PanelRight: markRaw(PanelRight),
  PanelTop: markRaw(PanelTop),
  PanelBottom: markRaw(PanelBottom),
  Expand: markRaw(Expand),
  // Collapse removed in lucide 1.0
  MoveUp: markRaw(MoveUp),
  MoveDown: markRaw(MoveDown),
  MoveLeft: markRaw(MoveLeft),
  MoveRight: markRaw(MoveRight),
  RotateCw: markRaw(RotateCw),
  RotateCcw: markRaw(RotateCcw),
  Command: markRaw(Command),
  GitBranch: markRaw(GitBranch),
  GitPullRequest: markRaw(GitPullRequest),
  GitCommit: markRaw(GitCommit),
  HardDrive: markRaw(HardDrive),
  CalendarDays: markRaw(CalendarDays),
  Timer: markRaw(Timer),
  CloudSun: markRaw(CloudSun),
  CloudMoon: markRaw(CloudMoon),
}

export interface IconEntry {
  name: string
  component: Component
}

export const iconEntries: IconEntry[] = Object.entries(registry).map(([name, component]) => ({
  name,
  component,
}))

export function getIcon(name: string): Component | undefined {
  return registry[name]
}

export const iconNames = Object.keys(registry)
